# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "workflow" ]
  pull_request:
    branches: [ "workflow" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src\NugetDependenciesChecker.sln
    - name: Build
      run: dotnet build --no-restore src\NugetDependenciesChecker.sln
    - name: Publish for win-x64
      run: dotnet publish src\NugetDependenciesChecker.csproj -c Release -r win-x64 -p:PublishSingleFile=true --self-contained true -o publish
    - name: Publish for linux-x64
      run: dotnet publish src\NugetDependenciesChecker.csproj -c Release -r linux-x64 -p:PublishSingleFile=true --self-contained true -o publish
    - name: Release
      uses: fnkr/github-action-ghr@v1
      env:
        GHR_COMPRESS: xz
        GHR_PATH: publish/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
